### ISSUE TITLE
Problems with inline math alignment

### ISSUE THREAD

**Issue by paolobrasolin** [paolobrasolin/jekyll-antex#18]
Some problems were had with inline math alignment:
* https://categorytheory.zulipchat.com/#narrow/stream/241990-general.3A-values/topic/goals.20and.20questions/near/267113655
* https://categorytheory.zulipchat.com/#narrow/stream/241990-general.3A-values/topic/goals.20and.20questions/near/267130103

@jonsterling if you can provide a sample of the specific LaTeX code that failed to render correctly that'd be really helpful for testing! :heart:

**Comment by jonsterling** [comment]
Here is an example that will not align correctly

    Blah blah $E$ blah blah $g$. 

You can detect the baseline misalignment if you try putting periods inside and outside the online math.

    $E.$. and $g.$.

Sadly i am not sure how this could be fixed without some information from the TeX state about where, within the box, the baseline actually falls. I wonder if you have any thoughts?

**Comment by paolobrasolin** [comment]
I ran a test with a `serif` font, a `sans-serif` font, and `CMU Serif` (Computer Modern) itself:

![image](https://user-images.githubusercontent.com/2499655/151258517-d8048bf2-3e1a-4724-88d6-0f70b09e7e31.png)

Yes, there seem to be some minor but perceptible misalignment. Let's zoom in:

![image](https://user-images.githubusercontent.com/2499655/151258603-f37e2d4d-7760-4a40-b2c8-a3a89424875a.png)

I believe the effect is due mostly to rounding errors in rendering calculations (especially since some points are SVG images and some are rendered by the font engine of the browser).

The mechanism `antex` uses to acquire metrics has some limitations, but I think there's no fundamental flaw in it except for the assumption that LaTeX is trustworthy (since the relation between boxes and ink depends completely on the common sense of the font designer).

I don't think I can do any better than this. :sweat_smile:

I'll close this @jonsterling but please do feel free to post some screenshots (and links perhaps?) if you're seeing deviations bigger than the ones above. Thanks!
