### ISSUE TITLE
Feedback on image compilation: show progress during build

### ISSUE THREAD

**Issue by tetrapharmakon** [paolobrasolin/jekyll-antex#9]

**Comment by paolobrasolin** [comment]
I think this is doable. Every snippet has a deterministic name so it would be possible to delay the rendering and process them all together on a hook (probably the `:post_render` of `:site`) and show a progress bar(!).

This is not trivial, though.

**Comment by tetrapharmakon** [comment]
Idk what's easier to code, but I guess a progress bar like

``` 
~$ █████████░░░░░░░░░░░░░░ image n of N processing 
```

would be fine. Just to know _how many_ files have to be compiled and measure the amount of coffee to put on. Being able to distinguish which snippets have been updated, and with a rough estimate of the time needed to compile one of the images, you have a (rough) estimate of how much time anTeX will need.
